export const ALL_EVENTS = 'ALL_EVENTS';
export const ALL_EVENTS_SUCCESS = 'ALL_EVENTS_SUCCESS';
export const EVENT_BY_ID = 'EVENT_BY_ID';
export const EVENT_BY_ID_SUCCESS = 'EVENT_BY_ID_SUCCESS';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';

export const SET_FILTER_CONDITIONS = 'SET_FILTER_CONDITIONS';
export const REMOVE_CONDITION = 'REMOVE_CONDITION';
